### ISSUE TITLE
NPM doesn't have latest version

### ISSUE THREAD

**Issue by MagneticLlama** [s-yadav/iv-viewer#112]
NPM has 2.0.1, while 2.1.1 is available in dist
https://github.com/s-yadav/iv-viewer/blob/master/dist/

**Comment by rslibed** [comment]
Will npm be updated?

**Comment by s-yadav** [comment]
Hey sure. Will update it today. Missed earlier and then forgot about it.

**Comment by s-yadav** [comment]
This is updated now. 🙂
