### ISSUE TITLE
Panning does not work on mobile chrome

### ISSUE THREAD

**Issue by jokerttu** [s-yadav/iv-viewer#2]
Mobile mediaquery hides the viewFinder. Move logic is under viewFinder code and it uses viewFinder height and width for calculations. When viewFinder is hidden browser gives 0 for width and height -> panning won't work.
Logic need to be changed so that the panning is done on image space and viewFinder is updated (if visible)

For fast fix I just changed the mediaquery so that viewFinder is always visible but just drawn outside of the view.
@media screen and (max-width: 767px) {
  .iv-snap-view {
    top: -9999px;
  }
}

**Comment by s-yadav** [comment]
Thanks @jokerttu

Needed a css change only, updated to

``` css
.iv-snap-view {
   z-index : -1;
   visibility:hidden;
}
```
