### ISSUE TITLE
No jquery requirement

### ISSUE THREAD

**Issue by amritk** [s-yadav/iv-viewer#26]
I've removed the jquery requirement here: https://github.com/amritk/ImageViewer
Let me know if you want me to make a pull request, its still messy but it works.

**Comment by s-yadav** [comment]
Yes, please!! That will be helpful :)

**Comment by amritk** [comment]
Sweet, I'll clean it up and make one some time this week.

**Comment by amritk** [comment]
Alright here you go https://github.com/s-yadav/ImageViewer/pull/27
