### ISSUE TITLE
highResolutionImage Doesn't seem to load (chrome)

### ISSUE THREAD

**Issue by tfm4th** [s-yadav/iv-viewer#29]
I can't get the data-high-res-src to work, nor does it seem to work in the demo.

**Comment by gogogoaldi** [comment]
Seems to be a mixup in the documentation. Use "data-high-res-img" instead:

`<img src="images/1.jpg" data-high-res-img="images/1_big.jpg" alt="" class="gallery-items">`

**Comment by s-yadav** [comment]
This is fixed. Closing this. data-high-res-src is the correct attribute on v2 now.
