### ISSUE TITLE
Close button background 

### ISSUE THREAD

**Issue by sziti** [s-yadav/iv-viewer#33]
Hi, firstly many thanks for this great viewer!

It is possible to add a gray or shaded backgorund
to the close button? like this:
https://www.freeiconspng.com/uploads/silver-close-button-png-15.png
I use ImageViewer for mostly white background documents
and hard to find a white button on the white.

Other thing: on Android smartphones the close button is
very small. It is possible to make it larger?

And the tird: It is possible to assign browser back button and
Android back button to close the viewer instead default history_back?

Thanks a lot,
Peter

**Comment by Erimus-Koo** [comment]
You can add this to iv-close in css:

```
    background: rgba(0, 0, 0, .1);
    border-radius: 20%;
```

You can make it more radius to get a circle, or add border to expand. Just like your example icon.

---

In my case, I use it on mobile, so I remove the transition, and edit it like below:

```

.iv-close {
    width: 48px;
    height: 48px;
    text-align: center;
    font: 100 36px/48px sans-serif;
    color: #FFF;
    text-shadow: 0px 0px 4px #000;
    position: absolute;
    right: 0;
    cursor: pointer;
    opacity: .5;
}

.iv-close:before {
    content: "×";
}

```

**Comment by s-yadav** [comment]
Closing this.
