### ISSUE TITLE
What is the minimum size for the initial image?

### ISSUE THREAD

**Issue by pmi123** [s-yadav/iv-viewer#39]
I tried using a small image, 102x132 pixels for the small image and a larger image 884x1151 for the larger image, and the zoom/pan did not work. Or, it was not visible? 

Are there optimum sizes for the two images?

Is there a necessary relationship between the two image sizes that needs to  be maintained for the plugin to work optimally?

Thanks!

Mark

**Comment by s-yadav** [comment]
There is no opinionated size for small image and large image, That depends on your use case, Though 102x132 looks so small size to be used as a small image. Also, you have to make sure they follow the exact ratio. Otherwise, you might get distortion while Large image is loading.
