### ISSUE TITLE
Position is not properly modified when zooming out

### ISSUE THREAD

**Issue by oparoz** [s-yadav/iv-viewer#4]
1. Load the official demo
2. Go to the bottom of the page -> Image mode
3. Zoom in on the ballerina
4. Pan to the right
5. Zoom out

The image is not centred at the same time it's zoomed out and all the sudden, the position is reset.

**Comment by s-yadav** [comment]
Zoom happens taking cursor position as zoom center point, but when image size reduces enough to fit into the container, it takes image center point as zoom center. That is causing a sudden flicker. 
Will work on the fix.

**Comment by s-yadav** [comment]
I have updated a new build with a fix. You can try it and let me know, if that fixed it. Will close this afterward.

**Comment by oparoz** [comment]
Works! Thank you.
