### ISSUE TITLE
Errors on using ImageViewer()

### ISSUE THREAD

**Issue by PyroGenesis** [s-yadav/iv-viewer#42]
I tried using this library using a script import as well as a npm dependency, however both times I ran into errors on calling the `ImageViewer()` function.

When using <script>:
`ImageViewer() is not a function`

When using npm:
`TypeError: Cannot call a class as a function`

**Comment by s-yadav** [comment]
Looks like there is a bundeling issue. Will check.

**Comment by 0xkrishna17** [comment]
@s-yadav Great solution.. But I'm too stuck at this. When will this be resolved as I need it urgently?
Thanks

**Comment by s-yadav** [comment]
@PyroGenesis @krishnaacc123 Adding as a npm dependency works as usual. 
Regarding script import you will have to use ImageViewer in following way
```js
new ImageViewer.default(container)

// FullScreen
new ImageViewer.FullScreenViewer()
```
This is because babel7 stopped supporting babel-plugin-add-module-exports. But I will check if I can create bundle which can be used directly as 
```js
new ImageViewer(container)
```

**Comment by s-yadav** [comment]
Released v2.0.0-beta4. Now you can just do 
Usage from script
```js
new ImageViewer(container)
```

But still if you are using require pattern you will have to do 
```js
const ImageViewer = require('iv-viewer').default; //This I added on doc.
```

For module imports it will remain same
```js
import ImageViewer from 'iv-viewer';
```

**Comment by krishnaacc123** [comment]
> Released v2.0.0-beta4. Now you can just do
> Usage from script
> 
> ```js
> new ImageViewer(container)
> ```
> 
> But still if you are using require pattern you will have to do
> 
> ```js
> const ImageViewer = require('iv-viewer').default; //This I added on doc.
> ```
> 
> For module imports it will remain same
> 
> ```js
> import ImageViewer from 'iv-viewer';
> ```

Thanks a ton.

**Comment by 0xkrishna17** [comment]
Thanks a ton @s-yadav

**Comment by PyroGenesis** [comment]
Thank you for the timely fix.

- I tested all 3 modes using script and all of them worked flawlessly. 
[I created this simple HTML file to do so.](https://github.com/s-yadav/iv-viewer/files/2961116/all_modes.zip)

- Next, I tested all 3 modes using npm
    The container and image modes worked properly, however fullscreen mode gave me this error:
    `TypeError: iv_viewer__WEBPACK_IMPORTED_MODULE_2___default.a.FullScreenViewer is not a constructor`

I'm using Angular 7 if that's any help

**Comment by s-yadav** [comment]
@PyroGenesis Can you show how you are importing FullScreenViewer ?

**Comment by PyroGenesis** [comment]
```js
import ImageViewer from 'iv-viewer';
```

```js
const viewer = new ImageViewer.FullScreenViewer({ /* options */ });
viewer.show('https://picsum.photos/300/200/?image=1026');
```

**Comment by s-yadav** [comment]
No, you have to do 
```js
import {FullScreenViewer} from 'iv-viewer';
```

**Comment by PyroGenesis** [comment]
You're right.
```js
import {FullScreenViewer} from 'iv-viewer';
```
```js
const viewer = new FullScreenViewer({ /* options */ });
viewer.show('https://picsum.photos/300/200/?image=1026');
```
worked perfectly.

Earlier I had tried importing `FullScreenViewer` but since I had done it without the `{}`, it had given me:
`TypeError: domElement.getAttribute is not a function`

Strangely, using `new ImageViewer.FullScreenViewer()` in script works, but `new FullScreenViewer()` gives me `Uncaught ReferenceError: FullScreenViewer is not defined`

Thanks for all your help!

**Comment by amritk** [comment]
hey @s-yadav the readme shows 
```
const viewer = FullScreenViewer(options); // check options section for supported options
```
When it should be 
```
const viewer = new FullScreenViewer(options); // check options section for supported options
```

**Comment by s-yadav** [comment]
Thanks for pointing out this. Will fix it.

**Comment by amritk** [comment]
yea it got me lol

**Comment by s-yadav** [comment]
Closing this issue, as documentation fixed on latest version.
