### ISSUE TITLE
Images are not removed

### ISSUE THREAD

**Issue by mea-alexanm** [s-yadav/iv-viewer#44]
Hello,

first I want to thank for this nice library, but I have one issue:
I have a list of images, which upon clicking on them I load into the image viewer. When loading the second image, it seems that the first one does not get removed. Having a look inot the debugger tools of the browser, it reveals that with every imageViewer.load a new image is added (I am only loading the image with one url, so no hi res image url present).
The images are added with the classes iv-image iv-small-image. Looking into the source code of iv-viewer in the method _loadImages, I can see that only the images with the following classes are removed from the dom iv-snap-image, iv-large-image. I guess thats the reason why the images stay there. Removing the snap image works as expected.

Any advice?

Thx
Markus

**Comment by s-yadav** [comment]
I will fix this. You can also raise a PR if you know the fix.

**Comment by mea-alexanm** [comment]
Hello,

thx for this. Well it depends: I don't know exactly how this iv-small-image is working in the new version as it seems that it was not there in the old (pre es6) one. There it seems also only the iv-large-image was there, even when no hi res image was loaded.

BR
Markus

**Comment by s-yadav** [comment]
Fixed in v2.0.0-beta5. Let me know if you find any other issue.

**Comment by mea-alexanm** [comment]
Works. Thanks for fixing this.

BR
MArkus
