### ISSUE TITLE
SnapImage handles

### ISSUE THREAD

**Issue by mea-alexanm** [s-yadav/iv-viewer#45]
Hello,

I have the issue in Firefox that even whenn zoom is 100% and the snap image is not shown, the cursor changes to a hand at the places where the snap image would normally be shown.

Thx
Markus

**Comment by s-yadav** [comment]
Will fix this.

**Comment by s-yadav** [comment]
Fixed in v2.0.0-beta5. Let me know if you find any other issue.

**Comment by mea-alexanm** [comment]
Works. Thx for fixing this.

BR
Markus
