### ISSUE TITLE
ScrollZoom not working

### ISSUE THREAD

**Issue by DeeFuse** [s-yadav/iv-viewer#46]
ScrollZomm isn't working in FF 66.0.2 with 2.0.0-beta5.
I narrowed down the problem to `e.wheelDelta` not `e.detail` not beeing available here:
https://github.com/s-yadav/iv-viewer/blob/master/lib/ImageViewer.js#L613

My quick fix would be to change it to `e.deltaY`

**Comment by s-yadav** [comment]
Fixed this as suggested on v2.0.0. Let me know if that works.
