### ISSUE TITLE
Image jumps when 1 finger remains after pinch-zooming

### ISSUE THREAD

**Issue by PAPLabs** [s-yadav/iv-viewer#55]
When pinch-zooming an image, the image tends to jump up/down/left/right at the end of the pinch.

I can reproduce this on mobile android chrome with all three examples of the demo at https://8ypwzryom0.codesandbox.io/

The issue may affect any touch device.

Problem happens when you are releasing pinch (release 1 of 2 fingers), but a touchmove event is sent before you release second finger. This happens unintentionally often enough with touch devices (and clumsy fingers).

Steps to reproduce :

1. use zoom at least once so the zoom level is > 100

2. do a pinch zoom in or out

3. release one finger

4. move the remaining finger

I have debugged it around and here is what happens in the code :

- First touch : imageSlider.startHandler is called, defining sx & sy, and also calling snapSlider.onStart which defines startHandleTop & startHandleLeft

- Pinch zoom : Slider.moveHandler does nothing because isSliderEnabled() returns false

- When one finger remains : slider moves using reference values from first touch, which are kinda broken by the zoom.

I have fixed it for my app with the following code, feel free to reuse or make your own proper fix.
1. _pinchAndZoom endListener
```js
const endListener = (eEnd) => {
    // unbind events
    events.pinchMove();
    events.pinchEnd();
    this._state.zooming = false;
    // properly resume move event if one finger remains
    if ( eEnd.touches.length == 1 )
        this._sliders.imageSlider.startHandler(eEnd);
};
```

2. I also had to adjust that line in Slider.startHandler :
```js
const isTouchEvent = (eStart.type === 'touchstart' || eStart.type === 'touchend');
```

**Comment by mvasigh** [comment]
I'd like to take this on!

**Comment by fracristaldibcame** [comment]
Good Morning the issue is again live, in attach my test

https://user-images.githubusercontent.com/51959198/119322262-c3645b00-bc7d-11eb-836f-510e0f283611.mp4

Browser: Google Chrome v90.0.4430.210
Device: LG-H930
Android: 8.0.0
Link demo tested: https://8ypwzryom0.codesandbox.io/fullscreen-mode/example.html

Steps to reproduce:
same of top description

thanks
F. Cristaldi
