### ISSUE TITLE
Uncaught ReferenceError: FullScreenViewer is not defined

### ISSUE THREAD

**Issue by csandreas1** [s-yadav/iv-viewer#78]
I use the standalone UMD build by including dist/iv-viewer.js and dist/iv-viewer.css in your page.

However when i call   const viewer = new FullScreenViewer(); i get : Uncaught ReferenceError: FullScreenViewer is not defined

**Comment by timhuangt** [comment]
try this:

viewer = new ImageViewer.FullScreenViewer();

**Comment by shaon-hossain45** [comment]
It's working --- thanks...
